# Generated by Django 3.1.5 on 2021-04-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyr', '0002_question_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='owner',
            field=models.CharField(default='ch1ck3n', max_length=100),
        ),
    ]
