# Generated by Django 3.1.5 on 2021-04-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyr', '0003_question_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.IntegerField(default=1)),
                ('side', models.CharField(default='left', max_length=10)),
                ('voter', models.CharField(default='left', max_length=64)),
            ],
        ),
    ]
