# Generated by Django 3.1.5 on 2021-04-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyr', '0005_auto_20210409_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='vt_l2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='vt_r2',
            field=models.IntegerField(default=0),
        ),
    ]
