# Generated by Django 3.1.5 on 2021-04-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyr', '0006_auto_20210410_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pub_data',
            field=models.CharField(default='2021-04-09', max_length=100),
        ),
    ]
